### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by jithendra-roy** [Cantera/mixmaster#3]
The aim to design this work frame is not mentioned and the expected outcome is no where discussed

**Comment by bryanwweber** [comment]
The GSoC idea related to this project is vague because we don't know what needs to be done here. For instance, I don't know if this software works right now. I think the first step for anyone who wants to propose to work on MixMaster is to get what's here working and see what it can do. You can see what the original version of Mixmaster was designed to do in this PDF: https://www.et.byu.edu/~tom/classes/641/Cantera/mixmaster.pdf
